version: '3'
services:
  user_info_service:
    container_name: "user_info_service"
    build:
      context: ./                 #指定dockerfile所在目录
      dockerfile: Dockerfile      #指定dockerfile文件名
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/src/userInfoService/logs:/logs
  